In [1]:
import numpy as np
from numpy import load
import matplotlib.pyplot as plt
from PIL import Image
import glob
import cv2

In [3]:
#!mkdir results10

In [4]:
files = glob.glob('*.npz')
i = 0
for f in files:
    while(i<2765):
        episode = load(f)
        rgb_static = episode["rgb_static"]
        print(i)
        print(f)
        im_rgb_static = Image.fromarray(rgb_static)
       
        if(i<10):
            im_rgb_static.save("results10/frame00000"+str(i)+".jpg")
        elif (9 < i < 100):
            im_rgb_static.save("results10/frame0000"+str(i)+".jpg")
        elif (99 < i < 1000):
            im_rgb_static.save("results10/frame000"+str(i)+".jpg")
        else:
            im_rgb_static.save("results10/frame00"+str(i)+".jpg")
            
        if(i==i):
            i = i+1
            break

0
episode_0360597.npz
1
episode_0360492.npz
2
episode_0359708.npz
3
episode_0358523.npz
4
episode_0361058.npz
5
episode_0359461.npz
6
episode_0360961.npz
7
episode_0359887.npz
8
episode_0359263.npz
9
episode_0360785.npz
10
episode_0359996.npz
11
episode_0360136.npz
12
episode_0360326.npz
13
episode_0360197.npz
14
episode_0360580.npz
15
episode_0359553.npz
16
episode_0358719.npz
17
episode_0358900.npz
18
episode_0358973.npz
19
episode_0360664.npz
20
episode_0360022.npz
21
episode_0359929.npz
22
episode_0359709.npz
23
episode_0361019.npz
24
episode_0358892.npz
25
episode_0359730.npz
26
episode_0359254.npz
27
episode_0360617.npz
28
episode_0360390.npz
29
episode_0360208.npz
30
episode_0358868.npz
31
episode_0359146.npz
32
episode_0359617.npz
33
episode_0360356.npz
34
episode_0359445.npz
35
episode_0361095.npz
36
episode_0358691.npz
37
episode_0359308.npz
38
episode_0358926.npz
39
episode_0358723.npz
40
episode_0360245.npz
41
episode_0359393.npz
42
episode_0360161.npz
43
episode_0359523.np

356
episode_0359661.npz
357
episode_0360046.npz
358
episode_0359178.npz
359
episode_0358771.npz
360
episode_0359211.npz
361
episode_0359177.npz
362
episode_0359222.npz
363
episode_0359183.npz
364
episode_0360293.npz
365
episode_0359513.npz
366
episode_0358578.npz
367
episode_0359097.npz
368
episode_0360753.npz
369
episode_0360634.npz
370
episode_0359591.npz
371
episode_0361010.npz
372
episode_0359531.npz
373
episode_0358972.npz
374
episode_0360023.npz
375
episode_0361077.npz
376
episode_0360055.npz
377
episode_0360522.npz
378
episode_0360864.npz
379
episode_0360032.npz
380
episode_0361023.npz
381
episode_0359558.npz
382
episode_0360378.npz
383
episode_0360159.npz
384
episode_0358615.npz
385
episode_0359350.npz
386
episode_0361174.npz
387
episode_0359942.npz
388
episode_0361221.npz
389
episode_0358899.npz
390
episode_0360740.npz
391
episode_0358971.npz
392
episode_0359780.npz
393
episode_0360942.npz
394
episode_0359993.npz
395
episode_0360950.npz
396
episode_0360875.npz
397
episode_0360

710
episode_0360813.npz
711
episode_0360237.npz
712
episode_0359720.npz
713
episode_0358846.npz
714
episode_0360372.npz
715
episode_0359835.npz
716
episode_0359355.npz
717
episode_0359033.npz
718
episode_0360854.npz
719
episode_0360012.npz
720
episode_0361147.npz
721
episode_0359689.npz
722
episode_0360673.npz
723
episode_0358920.npz
724
episode_0360530.npz
725
episode_0358981.npz
726
episode_0360275.npz
727
episode_0360930.npz
728
episode_0359798.npz
729
episode_0358727.npz
730
episode_0360655.npz
731
episode_0359000.npz
732
episode_0359939.npz
733
episode_0360375.npz
734
episode_0359945.npz
735
episode_0359017.npz
736
episode_0359283.npz
737
episode_0360988.npz
738
episode_0359436.npz
739
episode_0359936.npz
740
episode_0358858.npz
741
episode_0360849.npz
742
episode_0359314.npz
743
episode_0359649.npz
744
episode_0358705.npz
745
episode_0359694.npz
746
episode_0358845.npz
747
episode_0360605.npz
748
episode_0360538.npz
749
episode_0360927.npz
750
episode_0358607.npz
751
episode_0359

1089
episode_0360118.npz
1090
episode_0361059.npz
1091
episode_0358560.npz
1092
episode_0359667.npz
1093
episode_0359399.npz
1094
episode_0358862.npz
1095
episode_0360998.npz
1096
episode_0358514.npz
1097
episode_0360539.npz
1098
episode_0358574.npz
1099
episode_0359845.npz
1100
episode_0359262.npz
1101
episode_0359186.npz
1102
episode_0360640.npz
1103
episode_0361153.npz
1104
episode_0360626.npz
1105
episode_0360465.npz
1106
episode_0360436.npz
1107
episode_0360486.npz
1108
episode_0360054.npz
1109
episode_0360611.npz
1110
episode_0359983.npz
1111
episode_0358760.npz
1112
episode_0360529.npz
1113
episode_0358938.npz
1114
episode_0359557.npz
1115
episode_0360417.npz
1116
episode_0360600.npz
1117
episode_0359176.npz
1118
episode_0360206.npz
1119
episode_0361122.npz
1120
episode_0360379.npz
1121
episode_0360130.npz
1122
episode_0359554.npz
1123
episode_0358551.npz
1124
episode_0359159.npz
1125
episode_0359750.npz
1126
episode_0360965.npz
1127
episode_0360801.npz
1128
episode_0359470.npz


1488
episode_0360716.npz
1489
episode_0360000.npz
1490
episode_0359475.npz
1491
episode_0359964.npz
1492
episode_0360163.npz
1493
episode_0359203.npz
1494
episode_0360516.npz
1495
episode_0360015.npz
1496
episode_0360893.npz
1497
episode_0358515.npz
1498
episode_0359438.npz
1499
episode_0360826.npz
1500
episode_0360348.npz
1501
episode_0360606.npz
1502
episode_0358988.npz
1503
episode_0359081.npz
1504
episode_0359145.npz
1505
episode_0360285.npz
1506
episode_0359196.npz
1507
episode_0361028.npz
1508
episode_0359818.npz
1509
episode_0359427.npz
1510
episode_0359975.npz
1511
episode_0359128.npz
1512
episode_0360566.npz
1513
episode_0359444.npz
1514
episode_0358668.npz
1515
episode_0358960.npz
1516
episode_0359343.npz
1517
episode_0359856.npz
1518
episode_0360633.npz
1519
episode_0359508.npz
1520
episode_0360337.npz
1521
episode_0360019.npz
1522
episode_0359784.npz
1523
episode_0358612.npz
1524
episode_0359541.npz
1525
episode_0359615.npz
1526
episode_0360354.npz
1527
episode_0360944.npz


1870
episode_0361161.npz
1871
episode_0360232.npz
1872
episode_0358759.npz
1873
episode_0359337.npz
1874
episode_0358675.npz
1875
episode_0358594.npz
1876
episode_0358661.npz
1877
episode_0360669.npz
1878
episode_0360804.npz
1879
episode_0358519.npz
1880
episode_0360239.npz
1881
episode_0360980.npz
1882
episode_0359622.npz
1883
episode_0359069.npz
1884
episode_0359899.npz
1885
episode_0361187.npz
1886
episode_0359095.npz
1887
episode_0358970.npz
1888
episode_0360457.npz
1889
episode_0359205.npz
1890
episode_0360086.npz
1891
episode_0360298.npz
1892
episode_0358689.npz
1893
episode_0360074.npz
1894
episode_0361068.npz
1895
episode_0361097.npz
1896
episode_0359808.npz
1897
episode_0359332.npz
1898
episode_0359932.npz
1899
episode_0360703.npz
1900
episode_0361180.npz
1901
episode_0359088.npz
1902
episode_0361136.npz
1903
episode_0358782.npz
1904
episode_0360576.npz
1905
episode_0360636.npz
1906
episode_0360933.npz
1907
episode_0360564.npz
1908
episode_0359723.npz
1909
episode_0359603.npz


2254
episode_0359637.npz
2255
episode_0360491.npz
2256
episode_0359691.npz
2257
episode_0360524.npz
2258
episode_0359501.npz
2259
episode_0359421.npz
2260
episode_0359948.npz
2261
episode_0360790.npz
2262
episode_0359134.npz
2263
episode_0359300.npz
2264
episode_0359041.npz
2265
episode_0359674.npz
2266
episode_0359910.npz
2267
episode_0360920.npz
2268
episode_0359072.npz
2269
episode_0359746.npz
2270
episode_0360969.npz
2271
episode_0360092.npz
2272
episode_0360752.npz
2273
episode_0360928.npz
2274
episode_0359473.npz
2275
episode_0360903.npz
2276
episode_0358879.npz
2277
episode_0359309.npz
2278
episode_0360205.npz
2279
episode_0358848.npz
2280
episode_0360494.npz
2281
episode_0359466.npz
2282
episode_0358842.npz
2283
episode_0358655.npz
2284
episode_0360802.npz
2285
episode_0360582.npz
2286
episode_0359045.npz
2287
episode_0361037.npz
2288
episode_0358528.npz
2289
episode_0359161.npz
2290
episode_0359038.npz
2291
episode_0360758.npz
2292
episode_0361135.npz
2293
episode_0360624.npz


2633
episode_0358751.npz
2634
episode_0358671.npz
2635
episode_0358969.npz
2636
episode_0360924.npz
2637
episode_0361128.npz
2638
episode_0359500.npz
2639
episode_0358913.npz
2640
episode_0361247.npz
2641
episode_0360760.npz
2642
episode_0359842.npz
2643
episode_0358690.npz
2644
episode_0359647.npz
2645
episode_0358810.npz
2646
episode_0360292.npz
2647
episode_0358764.npz
2648
episode_0359012.npz
2649
episode_0360467.npz
2650
episode_0359728.npz
2651
episode_0359666.npz
2652
episode_0360066.npz
2653
episode_0359758.npz
2654
episode_0361242.npz
2655
episode_0361193.npz
2656
episode_0360628.npz
2657
episode_0360902.npz
2658
episode_0361124.npz
2659
episode_0360889.npz
2660
episode_0358531.npz
2661
episode_0359580.npz
2662
episode_0360454.npz
2663
episode_0360656.npz
2664
episode_0360896.npz
2665
episode_0361029.npz
2666
episode_0358564.npz
2667
episode_0360029.npz
2668
episode_0358834.npz
2669
episode_0359267.npz
2670
episode_0359950.npz
2671
episode_0360891.npz
2672
episode_0358940.npz


In [5]:
files = glob.glob('*.npz')
i = 0
for f in files:
    while(i<2000):
        episode = load(f)
        d_static = episode["depth_static"]
        print(i)
        print(f)
        im_depth_static = Image.fromarray((d_static * 255).astype(np.uint8))
       
        if(i<10):
            im_depth_static.save("results10/depth00000"+str(i)+".png")
        elif (9 < i < 100):
            im_depth_static.save("results10/depth0000"+str(i)+".png")
        elif (99 < i < 1000):
            im_depth_static.save("results10/depth000"+str(i)+".png")
        else:
            im_depth_static.save("results10/depth00"+str(i)+".png")
            
        if(i==i):
            i = i+1
            break

0
episode_0360597.npz
1
episode_0360492.npz
2
episode_0359708.npz
3
episode_0358523.npz
4
episode_0361058.npz
5
episode_0359461.npz
6
episode_0360961.npz
7
episode_0359887.npz
8
episode_0359263.npz
9
episode_0360785.npz
10
episode_0359996.npz
11
episode_0360136.npz
12
episode_0360326.npz
13
episode_0360197.npz
14
episode_0360580.npz
15
episode_0359553.npz
16
episode_0358719.npz
17
episode_0358900.npz
18
episode_0358973.npz
19
episode_0360664.npz
20
episode_0360022.npz
21
episode_0359929.npz
22
episode_0359709.npz
23
episode_0361019.npz
24
episode_0358892.npz
25
episode_0359730.npz
26
episode_0359254.npz
27
episode_0360617.npz
28
episode_0360390.npz
29
episode_0360208.npz
30
episode_0358868.npz
31
episode_0359146.npz
32
episode_0359617.npz
33
episode_0360356.npz
34
episode_0359445.npz
35
episode_0361095.npz
36
episode_0358691.npz
37
episode_0359308.npz
38
episode_0358926.npz
39
episode_0358723.npz
40
episode_0360245.npz
41
episode_0359393.npz
42
episode_0360161.npz
43
episode_0359523.np

361
episode_0359177.npz
362
episode_0359222.npz
363
episode_0359183.npz
364
episode_0360293.npz
365
episode_0359513.npz
366
episode_0358578.npz
367
episode_0359097.npz
368
episode_0360753.npz
369
episode_0360634.npz
370
episode_0359591.npz
371
episode_0361010.npz
372
episode_0359531.npz
373
episode_0358972.npz
374
episode_0360023.npz
375
episode_0361077.npz
376
episode_0360055.npz
377
episode_0360522.npz
378
episode_0360864.npz
379
episode_0360032.npz
380
episode_0361023.npz
381
episode_0359558.npz
382
episode_0360378.npz
383
episode_0360159.npz
384
episode_0358615.npz
385
episode_0359350.npz
386
episode_0361174.npz
387
episode_0359942.npz
388
episode_0361221.npz
389
episode_0358899.npz
390
episode_0360740.npz
391
episode_0358971.npz
392
episode_0359780.npz
393
episode_0360942.npz
394
episode_0359993.npz
395
episode_0360950.npz
396
episode_0360875.npz
397
episode_0360441.npz
398
episode_0360344.npz
399
episode_0361076.npz
400
episode_0360936.npz
401
episode_0358660.npz
402
episode_0359

719
episode_0360012.npz
720
episode_0361147.npz
721
episode_0359689.npz
722
episode_0360673.npz
723
episode_0358920.npz
724
episode_0360530.npz
725
episode_0358981.npz
726
episode_0360275.npz
727
episode_0360930.npz
728
episode_0359798.npz
729
episode_0358727.npz
730
episode_0360655.npz
731
episode_0359000.npz
732
episode_0359939.npz
733
episode_0360375.npz
734
episode_0359945.npz
735
episode_0359017.npz
736
episode_0359283.npz
737
episode_0360988.npz
738
episode_0359436.npz
739
episode_0359936.npz
740
episode_0358858.npz
741
episode_0360849.npz
742
episode_0359314.npz
743
episode_0359649.npz
744
episode_0358705.npz
745
episode_0359694.npz
746
episode_0358845.npz
747
episode_0360605.npz
748
episode_0360538.npz
749
episode_0360927.npz
750
episode_0358607.npz
751
episode_0359787.npz
752
episode_0359905.npz
753
episode_0359690.npz
754
episode_0358991.npz
755
episode_0358496.npz
756
episode_0359322.npz
757
episode_0360382.npz
758
episode_0360044.npz
759
episode_0359142.npz
760
episode_0361

1083
episode_0358572.npz
1084
episode_0358547.npz
1085
episode_0360797.npz
1086
episode_0358715.npz
1087
episode_0359654.npz
1088
episode_0358509.npz
1089
episode_0360118.npz
1090
episode_0361059.npz
1091
episode_0358560.npz
1092
episode_0359667.npz
1093
episode_0359399.npz
1094
episode_0358862.npz
1095
episode_0360998.npz
1096
episode_0358514.npz
1097
episode_0360539.npz
1098
episode_0358574.npz
1099
episode_0359845.npz
1100
episode_0359262.npz
1101
episode_0359186.npz
1102
episode_0360640.npz
1103
episode_0361153.npz
1104
episode_0360626.npz
1105
episode_0360465.npz
1106
episode_0360436.npz
1107
episode_0360486.npz
1108
episode_0360054.npz
1109
episode_0360611.npz
1110
episode_0359983.npz
1111
episode_0358760.npz
1112
episode_0360529.npz
1113
episode_0358938.npz
1114
episode_0359557.npz
1115
episode_0360417.npz
1116
episode_0360600.npz
1117
episode_0359176.npz
1118
episode_0360206.npz
1119
episode_0361122.npz
1120
episode_0360379.npz
1121
episode_0360130.npz
1122
episode_0359554.npz


1437
episode_0358526.npz
1438
episode_0360831.npz
1439
episode_0361236.npz
1440
episode_0361198.npz
1441
episode_0358677.npz
1442
episode_0361158.npz
1443
episode_0358983.npz
1444
episode_0359811.npz
1445
episode_0358699.npz
1446
episode_0359625.npz
1447
episode_0360519.npz
1448
episode_0360113.npz
1449
episode_0360210.npz
1450
episode_0360352.npz
1451
episode_0360087.npz
1452
episode_0361212.npz
1453
episode_0359839.npz
1454
episode_0358828.npz
1455
episode_0360422.npz
1456
episode_0359060.npz
1457
episode_0359407.npz
1458
episode_0360039.npz
1459
episode_0358954.npz
1460
episode_0359432.npz
1461
episode_0359129.npz
1462
episode_0358508.npz
1463
episode_0360493.npz
1464
episode_0360722.npz
1465
episode_0359182.npz
1466
episode_0358979.npz
1467
episode_0361204.npz
1468
episode_0359492.npz
1469
episode_0358708.npz
1470
episode_0360151.npz
1471
episode_0360825.npz
1472
episode_0358935.npz
1473
episode_0359464.npz
1474
episode_0361126.npz
1475
episode_0360126.npz
1476
episode_0360111.npz


1805
episode_0360461.npz
1806
episode_0360986.npz
1807
episode_0359400.npz
1808
episode_0359989.npz
1809
episode_0359278.npz
1810
episode_0360135.npz
1811
episode_0358824.npz
1812
episode_0361121.npz
1813
episode_0359172.npz
1814
episode_0359626.npz
1815
episode_0361006.npz
1816
episode_0360146.npz
1817
episode_0360314.npz
1818
episode_0360095.npz
1819
episode_0360216.npz
1820
episode_0360001.npz
1821
episode_0359261.npz
1822
episode_0359685.npz
1823
episode_0361145.npz
1824
episode_0359259.npz
1825
episode_0358857.npz
1826
episode_0360498.npz
1827
episode_0359821.npz
1828
episode_0359481.npz
1829
episode_0359719.npz
1830
episode_0359498.npz
1831
episode_0360301.npz
1832
episode_0359547.npz
1833
episode_0359121.npz
1834
episode_0359668.npz
1835
episode_0359165.npz
1836
episode_0359846.npz
1837
episode_0359113.npz
1838
episode_0360270.npz
1839
episode_0358507.npz
1840
episode_0360613.npz
1841
episode_0359483.npz
1842
episode_0360874.npz
1843
episode_0359084.npz
1844
episode_0359865.npz


In [6]:
!mkdir results11

In [7]:
files = glob.glob('*.npz')
i = 0
for f in files:
    while(i<2000):
        episode = load(f)
        rgb_static = episode["rgb_static"]
        print(i)
        print(f)
        im_rgb_static = Image.fromarray(rgb_static)
       
        if(i<10):
            im_rgb_static.save("results11/frame00000"+str(i)+".jpg")
        elif (9 < i < 100):
            im_rgb_static.save("results11/frame0000"+str(i)+".jpg")
        elif (99 < i < 1000):
            im_rgb_static.save("results11/frame000"+str(i)+".jpg")
        else:
            im_rgb_static.save("results11/frame00"+str(i)+".jpg")
            
        if(i==i):
            i = i+1
            break

0
episode_0360597.npz
1
episode_0360492.npz
2
episode_0359708.npz
3
episode_0358523.npz
4
episode_0361058.npz
5
episode_0359461.npz
6
episode_0360961.npz
7
episode_0359887.npz
8
episode_0359263.npz
9
episode_0360785.npz
10
episode_0359996.npz
11
episode_0360136.npz
12
episode_0360326.npz
13
episode_0360197.npz
14
episode_0360580.npz
15
episode_0359553.npz
16
episode_0358719.npz
17
episode_0358900.npz
18
episode_0358973.npz
19
episode_0360664.npz
20
episode_0360022.npz
21
episode_0359929.npz
22
episode_0359709.npz
23
episode_0361019.npz
24
episode_0358892.npz
25
episode_0359730.npz
26
episode_0359254.npz
27
episode_0360617.npz
28
episode_0360390.npz
29
episode_0360208.npz
30
episode_0358868.npz
31
episode_0359146.npz
32
episode_0359617.npz
33
episode_0360356.npz
34
episode_0359445.npz
35
episode_0361095.npz
36
episode_0358691.npz
37
episode_0359308.npz
38
episode_0358926.npz
39
episode_0358723.npz
40
episode_0360245.npz
41
episode_0359393.npz
42
episode_0360161.npz
43
episode_0359523.np

392
episode_0359780.npz
393
episode_0360942.npz
394
episode_0359993.npz
395
episode_0360950.npz
396
episode_0360875.npz
397
episode_0360441.npz
398
episode_0360344.npz
399
episode_0361076.npz
400
episode_0360936.npz
401
episode_0358660.npz
402
episode_0359457.npz
403
episode_0359246.npz
404
episode_0358499.npz
405
episode_0358901.npz
406
episode_0360090.npz
407
episode_0359815.npz
408
episode_0360590.npz
409
episode_0359387.npz
410
episode_0359441.npz
411
episode_0359679.npz
412
episode_0360434.npz
413
episode_0359596.npz
414
episode_0359249.npz
415
episode_0358501.npz
416
episode_0358793.npz
417
episode_0360225.npz
418
episode_0358915.npz
419
episode_0359052.npz
420
episode_0361071.npz
421
episode_0360414.npz
422
episode_0358796.npz
423
episode_0358805.npz
424
episode_0359458.npz
425
episode_0358567.npz
426
episode_0359474.npz
427
episode_0359371.npz
428
episode_0358847.npz
429
episode_0359810.npz
430
episode_0361237.npz
431
episode_0360112.npz
432
episode_0359163.npz
433
episode_0359

793
episode_0360271.npz
794
episode_0360463.npz
795
episode_0359190.npz
796
episode_0360762.npz
797
episode_0359570.npz
798
episode_0358765.npz
799
episode_0360668.npz
800
episode_0358975.npz
801
episode_0359893.npz
802
episode_0361084.npz
803
episode_0359168.npz
804
episode_0360994.npz
805
episode_0358802.npz
806
episode_0360400.npz
807
episode_0359058.npz
808
episode_0359994.npz
809
episode_0358779.npz
810
episode_0360899.npz
811
episode_0359083.npz
812
episode_0359120.npz
813
episode_0359863.npz
814
episode_0359377.npz
815
episode_0360556.npz
816
episode_0358489.npz
817
episode_0358886.npz
818
episode_0359943.npz
819
episode_0359536.npz
820
episode_0360545.npz
821
episode_0360061.npz
822
episode_0360647.npz
823
episode_0360918.npz
824
episode_0360959.npz
825
episode_0359237.npz
826
episode_0359881.npz
827
episode_0360764.npz
828
episode_0360601.npz
829
episode_0359293.npz
830
episode_0359836.npz
831
episode_0360866.npz
832
episode_0359852.npz
833
episode_0360787.npz
834
episode_0359

1193
episode_0359218.npz
1194
episode_0360676.npz
1195
episode_0359285.npz
1196
episode_0360026.npz
1197
episode_0359490.npz
1198
episode_0359026.npz
1199
episode_0361144.npz
1200
episode_0360080.npz
1201
episode_0361085.npz
1202
episode_0361089.npz
1203
episode_0360886.npz
1204
episode_0360723.npz
1205
episode_0360286.npz
1206
episode_0359915.npz
1207
episode_0361101.npz
1208
episode_0358816.npz
1209
episode_0358800.npz
1210
episode_0359725.npz
1211
episode_0359366.npz
1212
episode_0360214.npz
1213
episode_0358575.npz
1214
episode_0358498.npz
1215
episode_0360678.npz
1216
episode_0359173.npz
1217
episode_0358875.npz
1218
episode_0360919.npz
1219
episode_0360076.npz
1220
episode_0360661.npz
1221
episode_0360085.npz
1222
episode_0360781.npz
1223
episode_0359824.npz
1224
episode_0360846.npz
1225
episode_0360230.npz
1226
episode_0359565.npz
1227
episode_0360370.npz
1228
episode_0360567.npz
1229
episode_0359412.npz
1230
episode_0358936.npz
1231
episode_0359158.npz
1232
episode_0361146.npz


1601
episode_0360824.npz
1602
episode_0358636.npz
1603
episode_0359931.npz
1604
episode_0359197.npz
1605
episode_0360194.npz
1606
episode_0359618.npz
1607
episode_0359274.npz
1608
episode_0360209.npz
1609
episode_0358512.npz
1610
episode_0360203.npz
1611
episode_0359783.npz
1612
episode_0360319.npz
1613
episode_0361205.npz
1614
episode_0358540.npz
1615
episode_0360411.npz
1616
episode_0358867.npz
1617
episode_0360698.npz
1618
episode_0359339.npz
1619
episode_0358896.npz
1620
episode_0359219.npz
1621
episode_0359701.npz
1622
episode_0358742.npz
1623
episode_0360561.npz
1624
episode_0361009.npz
1625
episode_0361139.npz
1626
episode_0359449.npz
1627
episode_0359733.npz
1628
episode_0358732.npz
1629
episode_0358486.npz
1630
episode_0361075.npz
1631
episode_0358625.npz
1632
episode_0359853.npz
1633
episode_0360445.npz
1634
episode_0358758.npz
1635
episode_0359286.npz
1636
episode_0359063.npz
1637
episode_0361081.npz
1638
episode_0358790.npz
1639
episode_0361231.npz
1640
episode_0358776.npz


In [8]:
file = load("episode_0359887.npz")

In [9]:
print(file)

In [10]:
rgb_gripper = file["rgb_gripper"]

In [12]:
depth_gripeer = file["depth_gripper"]

In [11]:
print(rgb_gripper)

[[[153 153 153]
  [153 153 153]
  [153 153 153]
  ...
  [155 155 155]
  [155 155 155]
  [155 155 155]]

 [[113  86  56]
  [114  86  57]
  [169 169 169]
  ...
  [142 104  67]
  [144 105  68]
  [144 106  67]]

 [[111  84  55]
  [112  84  55]
  [169 169 169]
  ...
  [143 104  68]
  [144 106  69]
  [143 105  66]]

 ...

 [[157 120  82]
  [159 122  82]
  [162 124  83]
  ...
  [162 123  82]
  [162 123  83]
  [166 127  86]]

 [[163 124  83]
  [162 123  82]
  [161 122  82]
  ...
  [165 126  85]
  [162 123  82]
  [164 126  85]]

 [[165 126  85]
  [165 126  85]
  [164 126  85]
  ...
  [168 129  88]
  [164 125  84]
  [163 125  84]]]


In [15]:
files = glob.glob("episode_"+"*.npz")


i = 0
for f in files:
    while(i<2000):
        episode = load(f)
        print(i)
        print(f)          
        if(i==i):
            i = i+1
            break

0
episode_0360597.npz
1
episode_0360492.npz
2
episode_0359708.npz
3
episode_0358523.npz
4
episode_0361058.npz
5
episode_0359461.npz
6
episode_0360961.npz
7
episode_0359887.npz
8
episode_0359263.npz
9
episode_0360785.npz
10
episode_0359996.npz
11
episode_0360136.npz
12
episode_0360326.npz
13
episode_0360197.npz
14
episode_0360580.npz
15
episode_0359553.npz
16
episode_0358719.npz
17
episode_0358900.npz
18
episode_0358973.npz
19
episode_0360664.npz
20
episode_0360022.npz
21
episode_0359929.npz
22
episode_0359709.npz
23
episode_0361019.npz
24
episode_0358892.npz
25
episode_0359730.npz
26
episode_0359254.npz
27
episode_0360617.npz
28
episode_0360390.npz
29
episode_0360208.npz
30
episode_0358868.npz
31
episode_0359146.npz
32
episode_0359617.npz
33
episode_0360356.npz
34
episode_0359445.npz
35
episode_0361095.npz
36
episode_0358691.npz
37
episode_0359308.npz
38
episode_0358926.npz
39
episode_0358723.npz
40
episode_0360245.npz
41
episode_0359393.npz
42
episode_0360161.npz
43
episode_0359523.np

In [16]:
ls

episode_0358482.npz  episode_0359410.npz  episode_0360338.npz
episode_0358483.npz  episode_0359411.npz  episode_0360339.npz
episode_0358484.npz  episode_0359412.npz  episode_0360340.npz
episode_0358485.npz  episode_0359413.npz  episode_0360341.npz
episode_0358486.npz  episode_0359414.npz  episode_0360342.npz
episode_0358487.npz  episode_0359415.npz  episode_0360343.npz
episode_0358488.npz  episode_0359416.npz  episode_0360344.npz
episode_0358489.npz  episode_0359417.npz  episode_0360345.npz
episode_0358490.npz  episode_0359418.npz  episode_0360346.npz
episode_0358491.npz  episode_0359419.npz  episode_0360347.npz
episode_0358492.npz  episode_0359420.npz  episode_0360348.npz
episode_0358493.npz  episode_0359421.npz  episode_0360349.npz
episode_0358494.npz  episode_0359422.npz  episode_0360350.npz
episode_0358495.npz  episode_0359423.npz  episode_0360351.npz
episode_0358496.npz  episode_0359424.npz  episode_0360352.npz
episode_0358497.npz  episode_0359425.npz  episode_0360353.npz
episode_

In [21]:
path = "images/*.*"
my_list = []
for file in sorted(glob.glob(path)):
    print(file)


images/episode_0358482.npz
images/episode_0358483.npz
images/episode_0358484.npz
images/episode_0358485.npz
images/episode_0358486.npz
images/episode_0358487.npz
images/episode_0358488.npz
images/episode_0358489.npz
images/episode_0358490.npz
images/episode_0358491.npz
images/episode_0358492.npz
images/episode_0358493.npz
images/episode_0358494.npz
images/episode_0358495.npz
images/episode_0358496.npz
images/episode_0358497.npz
images/episode_0358498.npz
images/episode_0358499.npz
images/episode_0358500.npz
images/episode_0358501.npz
images/episode_0358502.npz
images/episode_0358503.npz
images/episode_0358504.npz
images/episode_0358505.npz
images/episode_0358506.npz
images/episode_0358507.npz
images/episode_0358508.npz
images/episode_0358509.npz
images/episode_0358510.npz
images/episode_0358511.npz
images/episode_0358512.npz
images/episode_0358513.npz
images/episode_0358514.npz
images/episode_0358515.npz
images/episode_0358516.npz
images/episode_0358517.npz
images/episode_0358518.npz
i

In [20]:
import os
# This is the path where all the files are stored.
folder_path = 'images'
# Open one of the files,
for data_file in sorted(os.listdir(folder_path)):
    print(data_file)

episode_0358482.npz
episode_0358483.npz
episode_0358484.npz
episode_0358485.npz
episode_0358486.npz
episode_0358487.npz
episode_0358488.npz
episode_0358489.npz
episode_0358490.npz
episode_0358491.npz
episode_0358492.npz
episode_0358493.npz
episode_0358494.npz
episode_0358495.npz
episode_0358496.npz
episode_0358497.npz
episode_0358498.npz
episode_0358499.npz
episode_0358500.npz
episode_0358501.npz
episode_0358502.npz
episode_0358503.npz
episode_0358504.npz
episode_0358505.npz
episode_0358506.npz
episode_0358507.npz
episode_0358508.npz
episode_0358509.npz
episode_0358510.npz
episode_0358511.npz
episode_0358512.npz
episode_0358513.npz
episode_0358514.npz
episode_0358515.npz
episode_0358516.npz
episode_0358517.npz
episode_0358518.npz
episode_0358519.npz
episode_0358520.npz
episode_0358521.npz
episode_0358522.npz
episode_0358523.npz
episode_0358524.npz
episode_0358525.npz
episode_0358526.npz
episode_0358527.npz
episode_0358528.npz
episode_0358529.npz
episode_0358530.npz
episode_0358531.npz


In [13]:
!mkdir gripper_results

In [14]:
files = sorted(glob.glob('*.npz'))
i = 0
for f in files:
    while(i<2000):
        episode = load(f)
        d_static = episode["depth_gripper"]
        print(i)
        print(f)
        im_depth_static = Image.fromarray((d_static * 255).astype(np.uint8))
       
        if(i<10):
            im_depth_static.save("gripper_results/depth00000"+str(i)+".png")
        elif (9 < i < 100):
            im_depth_static.save("gripper_results/depth0000"+str(i)+".png")
        elif (99 < i < 1000):
            im_depth_static.save("gripper_results/depth000"+str(i)+".png")
        else:
            im_depth_static.save("gripper_results/depth00"+str(i)+".png")
            
        if(i==i):
            i = i+1
            break

0
episode_0358482.npz
1
episode_0358483.npz
2
episode_0358484.npz
3
episode_0358485.npz
4
episode_0358486.npz
5
episode_0358487.npz
6
episode_0358488.npz
7
episode_0358489.npz
8
episode_0358490.npz
9
episode_0358491.npz
10
episode_0358492.npz
11
episode_0358493.npz
12
episode_0358494.npz
13
episode_0358495.npz
14
episode_0358496.npz
15
episode_0358497.npz
16
episode_0358498.npz
17
episode_0358499.npz
18
episode_0358500.npz
19
episode_0358501.npz
20
episode_0358502.npz
21
episode_0358503.npz
22
episode_0358504.npz
23
episode_0358505.npz
24
episode_0358506.npz
25
episode_0358507.npz
26
episode_0358508.npz
27
episode_0358509.npz
28
episode_0358510.npz
29
episode_0358511.npz
30
episode_0358512.npz
31
episode_0358513.npz
32
episode_0358514.npz
33
episode_0358515.npz
34
episode_0358516.npz
35
episode_0358517.npz
36
episode_0358518.npz
37
episode_0358519.npz
38
episode_0358520.npz
39
episode_0358521.npz
40
episode_0358522.npz
41
episode_0358523.npz
42
episode_0358524.npz
43
episode_0358525.np

371
episode_0358853.npz
372
episode_0358854.npz
373
episode_0358855.npz
374
episode_0358856.npz
375
episode_0358857.npz
376
episode_0358858.npz
377
episode_0358859.npz
378
episode_0358860.npz
379
episode_0358861.npz
380
episode_0358862.npz
381
episode_0358863.npz
382
episode_0358864.npz
383
episode_0358865.npz
384
episode_0358866.npz
385
episode_0358867.npz
386
episode_0358868.npz
387
episode_0358869.npz
388
episode_0358870.npz
389
episode_0358871.npz
390
episode_0358872.npz
391
episode_0358873.npz
392
episode_0358874.npz
393
episode_0358875.npz
394
episode_0358876.npz
395
episode_0358877.npz
396
episode_0358878.npz
397
episode_0358879.npz
398
episode_0358880.npz
399
episode_0358881.npz
400
episode_0358882.npz
401
episode_0358883.npz
402
episode_0358884.npz
403
episode_0358885.npz
404
episode_0358886.npz
405
episode_0358887.npz
406
episode_0358888.npz
407
episode_0358889.npz
408
episode_0358890.npz
409
episode_0358891.npz
410
episode_0358892.npz
411
episode_0358893.npz
412
episode_0358

761
episode_0359243.npz
762
episode_0359244.npz
763
episode_0359245.npz
764
episode_0359246.npz
765
episode_0359247.npz
766
episode_0359248.npz
767
episode_0359249.npz
768
episode_0359250.npz
769
episode_0359251.npz
770
episode_0359252.npz
771
episode_0359253.npz
772
episode_0359254.npz
773
episode_0359255.npz
774
episode_0359256.npz
775
episode_0359257.npz
776
episode_0359258.npz
777
episode_0359259.npz
778
episode_0359260.npz
779
episode_0359261.npz
780
episode_0359262.npz
781
episode_0359263.npz
782
episode_0359264.npz
783
episode_0359265.npz
784
episode_0359266.npz
785
episode_0359267.npz
786
episode_0359268.npz
787
episode_0359269.npz
788
episode_0359270.npz
789
episode_0359271.npz
790
episode_0359272.npz
791
episode_0359273.npz
792
episode_0359274.npz
793
episode_0359275.npz
794
episode_0359276.npz
795
episode_0359277.npz
796
episode_0359278.npz
797
episode_0359279.npz
798
episode_0359280.npz
799
episode_0359281.npz
800
episode_0359282.npz
801
episode_0359283.npz
802
episode_0359

1143
episode_0359625.npz
1144
episode_0359626.npz
1145
episode_0359627.npz
1146
episode_0359628.npz
1147
episode_0359629.npz
1148
episode_0359630.npz
1149
episode_0359631.npz
1150
episode_0359632.npz
1151
episode_0359633.npz
1152
episode_0359634.npz
1153
episode_0359635.npz
1154
episode_0359636.npz
1155
episode_0359637.npz
1156
episode_0359638.npz
1157
episode_0359639.npz
1158
episode_0359640.npz
1159
episode_0359641.npz
1160
episode_0359642.npz
1161
episode_0359643.npz
1162
episode_0359644.npz
1163
episode_0359645.npz
1164
episode_0359646.npz
1165
episode_0359647.npz
1166
episode_0359648.npz
1167
episode_0359649.npz
1168
episode_0359650.npz
1169
episode_0359651.npz
1170
episode_0359652.npz
1171
episode_0359653.npz
1172
episode_0359654.npz
1173
episode_0359655.npz
1174
episode_0359656.npz
1175
episode_0359657.npz
1176
episode_0359658.npz
1177
episode_0359659.npz
1178
episode_0359660.npz
1179
episode_0359661.npz
1180
episode_0359662.npz
1181
episode_0359663.npz
1182
episode_0359664.npz


1522
episode_0360004.npz
1523
episode_0360005.npz
1524
episode_0360006.npz
1525
episode_0360007.npz
1526
episode_0360008.npz
1527
episode_0360009.npz
1528
episode_0360010.npz
1529
episode_0360011.npz
1530
episode_0360012.npz
1531
episode_0360013.npz
1532
episode_0360014.npz
1533
episode_0360015.npz
1534
episode_0360016.npz
1535
episode_0360017.npz
1536
episode_0360018.npz
1537
episode_0360019.npz
1538
episode_0360020.npz
1539
episode_0360021.npz
1540
episode_0360022.npz
1541
episode_0360023.npz
1542
episode_0360024.npz
1543
episode_0360025.npz
1544
episode_0360026.npz
1545
episode_0360027.npz
1546
episode_0360028.npz
1547
episode_0360029.npz
1548
episode_0360030.npz
1549
episode_0360031.npz
1550
episode_0360032.npz
1551
episode_0360033.npz
1552
episode_0360034.npz
1553
episode_0360035.npz
1554
episode_0360036.npz
1555
episode_0360037.npz
1556
episode_0360038.npz
1557
episode_0360039.npz
1558
episode_0360040.npz
1559
episode_0360041.npz
1560
episode_0360042.npz
1561
episode_0360043.npz


1920
episode_0360402.npz
1921
episode_0360403.npz
1922
episode_0360404.npz
1923
episode_0360405.npz
1924
episode_0360406.npz
1925
episode_0360407.npz
1926
episode_0360408.npz
1927
episode_0360409.npz
1928
episode_0360410.npz
1929
episode_0360411.npz
1930
episode_0360412.npz
1931
episode_0360413.npz
1932
episode_0360414.npz
1933
episode_0360415.npz
1934
episode_0360416.npz
1935
episode_0360417.npz
1936
episode_0360418.npz
1937
episode_0360419.npz
1938
episode_0360420.npz
1939
episode_0360421.npz
1940
episode_0360422.npz
1941
episode_0360423.npz
1942
episode_0360424.npz
1943
episode_0360425.npz
1944
episode_0360426.npz
1945
episode_0360427.npz
1946
episode_0360428.npz
1947
episode_0360429.npz
1948
episode_0360430.npz
1949
episode_0360431.npz
1950
episode_0360432.npz
1951
episode_0360433.npz
1952
episode_0360434.npz
1953
episode_0360435.npz
1954
episode_0360436.npz
1955
episode_0360437.npz
1956
episode_0360438.npz
1957
episode_0360439.npz
1958
episode_0360440.npz
1959
episode_0360441.npz


In [15]:
files = sorted(glob.glob('*.npz'))
i = 0
for f in files:
    while(i<2000):
        episode = load(f)
        rgb_static = episode["rgb_static"]
        print(i)
        print(f)
        im_rgb_static = Image.fromarray(rgb_static)
       
        if(i<10):
            im_rgb_static.save("gripper_results/frame00000"+str(i)+".jpg")
        elif (9 < i < 100):
            im_rgb_static.save("gripper_results/frame0000"+str(i)+".jpg")
        elif (99 < i < 1000):
            im_rgb_static.save("gripper_results/frame000"+str(i)+".jpg")
        else:
            im_rgb_static.save("gripper_results/frame00"+str(i)+".jpg")
            
        if(i==i):
            i = i+1
            break

0
episode_0358482.npz
1
episode_0358483.npz
2
episode_0358484.npz
3
episode_0358485.npz
4
episode_0358486.npz
5
episode_0358487.npz
6
episode_0358488.npz
7
episode_0358489.npz
8
episode_0358490.npz
9
episode_0358491.npz
10
episode_0358492.npz
11
episode_0358493.npz
12
episode_0358494.npz
13
episode_0358495.npz
14
episode_0358496.npz
15
episode_0358497.npz
16
episode_0358498.npz
17
episode_0358499.npz
18
episode_0358500.npz
19
episode_0358501.npz
20
episode_0358502.npz
21
episode_0358503.npz
22
episode_0358504.npz
23
episode_0358505.npz
24
episode_0358506.npz
25
episode_0358507.npz
26
episode_0358508.npz
27
episode_0358509.npz
28
episode_0358510.npz
29
episode_0358511.npz
30
episode_0358512.npz
31
episode_0358513.npz
32
episode_0358514.npz
33
episode_0358515.npz
34
episode_0358516.npz
35
episode_0358517.npz
36
episode_0358518.npz
37
episode_0358519.npz
38
episode_0358520.npz
39
episode_0358521.npz
40
episode_0358522.npz
41
episode_0358523.npz
42
episode_0358524.npz
43
episode_0358525.np

411
episode_0358893.npz
412
episode_0358894.npz
413
episode_0358895.npz
414
episode_0358896.npz
415
episode_0358897.npz
416
episode_0358898.npz
417
episode_0358899.npz
418
episode_0358900.npz
419
episode_0358901.npz
420
episode_0358902.npz
421
episode_0358903.npz
422
episode_0358904.npz
423
episode_0358905.npz
424
episode_0358906.npz
425
episode_0358907.npz
426
episode_0358908.npz
427
episode_0358909.npz
428
episode_0358910.npz
429
episode_0358911.npz
430
episode_0358912.npz
431
episode_0358913.npz
432
episode_0358914.npz
433
episode_0358915.npz
434
episode_0358916.npz
435
episode_0358917.npz
436
episode_0358918.npz
437
episode_0358919.npz
438
episode_0358920.npz
439
episode_0358921.npz
440
episode_0358922.npz
441
episode_0358923.npz
442
episode_0358924.npz
443
episode_0358925.npz
444
episode_0358926.npz
445
episode_0358927.npz
446
episode_0358928.npz
447
episode_0358929.npz
448
episode_0358930.npz
449
episode_0358931.npz
450
episode_0358932.npz
451
episode_0358933.npz
452
episode_0358

816
episode_0359298.npz
817
episode_0359299.npz
818
episode_0359300.npz
819
episode_0359301.npz
820
episode_0359302.npz
821
episode_0359303.npz
822
episode_0359304.npz
823
episode_0359305.npz
824
episode_0359306.npz
825
episode_0359307.npz
826
episode_0359308.npz
827
episode_0359309.npz
828
episode_0359310.npz
829
episode_0359311.npz
830
episode_0359312.npz
831
episode_0359313.npz
832
episode_0359314.npz
833
episode_0359315.npz
834
episode_0359316.npz
835
episode_0359317.npz
836
episode_0359318.npz
837
episode_0359319.npz
838
episode_0359320.npz
839
episode_0359321.npz
840
episode_0359322.npz
841
episode_0359323.npz
842
episode_0359324.npz
843
episode_0359325.npz
844
episode_0359326.npz
845
episode_0359327.npz
846
episode_0359328.npz
847
episode_0359329.npz
848
episode_0359330.npz
849
episode_0359331.npz
850
episode_0359332.npz
851
episode_0359333.npz
852
episode_0359334.npz
853
episode_0359335.npz
854
episode_0359336.npz
855
episode_0359337.npz
856
episode_0359338.npz
857
episode_0359

1217
episode_0359699.npz
1218
episode_0359700.npz
1219
episode_0359701.npz
1220
episode_0359702.npz
1221
episode_0359703.npz
1222
episode_0359704.npz
1223
episode_0359705.npz
1224
episode_0359706.npz
1225
episode_0359707.npz
1226
episode_0359708.npz
1227
episode_0359709.npz
1228
episode_0359710.npz
1229
episode_0359711.npz
1230
episode_0359712.npz
1231
episode_0359713.npz
1232
episode_0359714.npz
1233
episode_0359715.npz
1234
episode_0359716.npz
1235
episode_0359717.npz
1236
episode_0359718.npz
1237
episode_0359719.npz
1238
episode_0359720.npz
1239
episode_0359721.npz
1240
episode_0359722.npz
1241
episode_0359723.npz
1242
episode_0359724.npz
1243
episode_0359725.npz
1244
episode_0359726.npz
1245
episode_0359727.npz
1246
episode_0359728.npz
1247
episode_0359729.npz
1248
episode_0359730.npz
1249
episode_0359731.npz
1250
episode_0359732.npz
1251
episode_0359733.npz
1252
episode_0359734.npz
1253
episode_0359735.npz
1254
episode_0359736.npz
1255
episode_0359737.npz
1256
episode_0359738.npz


1613
episode_0360095.npz
1614
episode_0360096.npz
1615
episode_0360097.npz
1616
episode_0360098.npz
1617
episode_0360099.npz
1618
episode_0360100.npz
1619
episode_0360101.npz
1620
episode_0360102.npz
1621
episode_0360103.npz
1622
episode_0360104.npz
1623
episode_0360105.npz
1624
episode_0360106.npz
1625
episode_0360107.npz
1626
episode_0360108.npz
1627
episode_0360109.npz
1628
episode_0360110.npz
1629
episode_0360111.npz
1630
episode_0360112.npz
1631
episode_0360113.npz
1632
episode_0360114.npz
1633
episode_0360115.npz
1634
episode_0360116.npz
1635
episode_0360117.npz
1636
episode_0360118.npz
1637
episode_0360119.npz
1638
episode_0360120.npz
1639
episode_0360121.npz
1640
episode_0360122.npz
1641
episode_0360123.npz
1642
episode_0360124.npz
1643
episode_0360125.npz
1644
episode_0360126.npz
1645
episode_0360127.npz
1646
episode_0360128.npz
1647
episode_0360129.npz
1648
episode_0360130.npz
1649
episode_0360131.npz
1650
episode_0360132.npz
1651
episode_0360133.npz
1652
episode_0360134.npz
